package com.isen.util.retry.mapper;

import com.isen.util.retry.pojo.RetryInfo;
import com.isen.util.retry.pojo.RetryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RetryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    long countByExample(RetryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int deleteByExample(RetryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int insert(RetryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int insertSelective(RetryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    List<RetryInfo> selectByExample(RetryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    RetryInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") RetryInfo record, @Param("example") RetryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int updateByExample(@Param("record") RetryInfo record, @Param("example") RetryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int updateByPrimaryKeySelective(RetryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    int updateByPrimaryKey(RetryInfo record);
}