package com.isen.util.retry.pojo;

import java.io.Serializable;
import java.util.Date;

public class RetryInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.id
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.class_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.method_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.parameters
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private String parameters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.create_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private Date createTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.update_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private Date updateTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.staus
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private Byte staus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.ramark
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private String ramark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retry_info.parameter_types
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private String parameterTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table retry_info
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.id
     *
     * @return the value of retry_info.id
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.id
     *
     * @param id the value for retry_info.id
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.class_name
     *
     * @return the value of retry_info.class_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.class_name
     *
     * @param className the value for retry_info.class_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.method_name
     *
     * @return the value of retry_info.method_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.method_name
     *
     * @param methodName the value for retry_info.method_name
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.parameters
     *
     * @return the value of retry_info.parameters
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.parameters
     *
     * @param parameters the value for retry_info.parameters
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setParameters(String parameters) {
        this.parameters = parameters == null ? null : parameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.create_tm
     *
     * @return the value of retry_info.create_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.create_tm
     *
     * @param createTm the value for retry_info.create_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.update_tm
     *
     * @return the value of retry_info.update_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public Date getUpdateTm() {
        return updateTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.update_tm
     *
     * @param updateTm the value for retry_info.update_tm
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setUpdateTm(Date updateTm) {
        this.updateTm = updateTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.staus
     *
     * @return the value of retry_info.staus
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public Byte getStaus() {
        return staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.staus
     *
     * @param staus the value for retry_info.staus
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setStaus(Byte staus) {
        this.staus = staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.ramark
     *
     * @return the value of retry_info.ramark
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public String getRamark() {
        return ramark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.ramark
     *
     * @param ramark the value for retry_info.ramark
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setRamark(String ramark) {
        this.ramark = ramark == null ? null : ramark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retry_info.parameter_types
     *
     * @return the value of retry_info.parameter_types
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public String getParameterTypes() {
        return parameterTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retry_info.parameter_types
     *
     * @param parameterTypes the value for retry_info.parameter_types
     *
     * @mbg.generated Fri Nov 02 10:03:16 CST 2018
     */
    public void setParameterTypes(String parameterTypes) {
        this.parameterTypes = parameterTypes == null ? null : parameterTypes.trim();
    }
}